apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
spec:
  selector:
    matchLabels:
      app: catalog-api
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: api
        image: piotrpaszekacr2022.azurecr.io/catalog-api:latest
        ports:
        - containerPort: 3000