apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
spec:
  selector:
    matchLabels:
      app: catalog-api
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: api
        image: piotrpaszekacr2022.azurecr.io/dotnet:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healts/ping
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3